Updated docs
Pixelrobin/php-feather pull request #47
Opened 2021-10-08 14:53 UTC by natewiebe13

Goal: Update documentation and create an upgrade doc that includes breaking changes

2021-10-10 00:38 UTC, michaelsavchuk requested changes
Overall this looks great! This is a lot more concise and clean than it was before. Thanks for your time and contributions.

I added some suggestions on ways I think the documentation could be made a little bit clearer in places. I'm open to feedback on those changes, just some thoughts. After this, I think we're ready to merge `v2.0` and publish (at least to an alpha) 🙌.

2021-10-10 00:38 UTC, michaelsavchuk commented on README.md
>  This project is still pretty young, and I'm still a little new to PHP. Suggestions are welcome!
I would remove this line for V2.
```suggestion
```

2021-10-10 00:38 UTC, michaelsavchuk commented on README.md
I think it would be good to clarify what exactly `getIcon()` does to avoid confusion.

````suggestion

`getIcon()` returns an `Icon` object. To render the icon html itself, either cast it as a string or call its `render()` function.

```php
$icons->getIcon('anchor'); // Returns an Icon object
$html = $icons->getIcon('anchor')->render(); // Returns the icon's html
echo $icons->getIcon('anchor'); // Outputs the icon's html, since it is cast as a string
```

2021-10-10 00:38 UTC, michaelsavchuk commented on README.md
>  ```
(Related to the comment on the lines before)

````suggestion

// Or use on a single icon to only affect that one
echo $icons->getIcon('alert-triangle')->setColor('red')->setAttribute('data-alert', 'true');
```
````

2021-10-10 00:38 UTC, michaelsavchuk commented on README.md
> +$icons->setAttributes(['stroke' => '#fff', 'stroke-width' => 2]);
I think adding comments here would make things a little bit clearer about what is going on, even if it's a little redundant. Thoughts?

```suggestion
// Use on the IconManager instance to set default attributes for all icons
$icons->setAttributes(['stroke' => '#fff', 'stroke-width' => 2]);
```

2021-10-12 14:28 UTC, natewiebe13 commented
Thanks for the feedback, looks great to me. Going to merge and release v2.0 alpha so we can accept any API suggestions before releasing v2.0 proper.

2021-10-12 14:28 UTC, merged